	<!DOCTYPE html>
	<html>
	<head>
		<title>Términos y Condiciones</title>
	</head>
	<body>
	<h2 style="text-align: center;"><strong>Términos y Condiciones de Uso</strong></h2>
	<p>&nbsp;</p><p><strong>INFORMACIÓN RELEVANTE</strong></p>
	<p>Es requisito necesario para la adquisición de los productos que se ofrecen en este sitio, que lea y acepte los siguientes Términos y Condiciones que a continuación se redactan. El uso de nuestros servicios así como la compra de nuestros productos implicará que usted ha leído y aceptado los Términos y Condiciones de Uso en el presente documento. Todas los productos &nbsp;que son ofrecidos por nuestro sitio web pudieran ser creadas, cobradas, enviadas o presentadas por una página web tercera y en tal caso estarían sujetas a sus propios Términos y Condiciones. En algunos casos, para adquirir un producto, será necesario el registro por parte del usuario, con ingreso de datos personales fidedignos y definición de una contraseña.</p><p>El usuario puede elegir y cambiar la clave para su acceso de administración de la cuenta en cualquier momento, en caso de que se haya registrado y que sea necesario para la compra de alguno de nuestros productos. https://tumedibot.com no asume la responsabilidad en caso de que entregue dicha clave a terceros.</p>
	<p>Todas las compras y transacciones que se lleven a cabo por medio de este sitio web, están sujetas a un proceso de confirmación y verificación, el cual podría incluir la verificación del stock y disponibilidad de producto, validación de la forma de pago, validación de la factura (en caso de existir) y el cumplimiento de las condiciones requeridas por el medio de pago seleccionado. En algunos casos puede que se requiera una verificación por medio de correo electrónico.</p>
	<p>Los precios de los productos ofrecidos en esta Tienda Online es válido solamente en las compras realizadas en este sitio web.</p>
	<p><strong>LICENCIA</strong></p>
	<p>medibot.com&nbsp; a través de su sitio web concede una licencia para que los usuarios utilicen&nbsp; los productos que son vendidos en este sitio web de acuerdo a los Términos y Condiciones que se describen en este documento.</p>
	<p><strong>USO NO AUTORIZADO</strong></p>
	<p>En caso de que aplique (para venta de software, templetes, u otro producto de diseño y programación) usted no puede colocar uno de nuestros productos, modificado o sin modificar, en un CD, sitio web o ningún otro medio y ofrecerlos para la redistribución o la reventa de ningún tipo.</p>
	<p><strong>DECLARACIÓN Y RESPONSABILIDAD DEL PRESTADOR DE SERVICIOS</strong></p> 
        <p>La intención de la Aplicación Web es mostrar al Destinatario de Servicios, sólo con fines informativos, las sugerencias de enfermedades y afecciones que pueden estar directamente relacionadas con los síntomas de un órgano de la anatomía humana indicados por el Destinatario de Servicios durante el llenado del formulario para presentar el Diagnóstico Virtual.</p>
        <p>Llenar el formulario de síntomas de enfermedades relacionas con algún órgano humano, el Diagnóstico Virtual y todos los contenidos publicados en la Aplicación Web son de carácter exclusivamente informativo y educativo y en ningún caso deben interpretarse o tratarse como un asesoramiento, consulta o diagnóstico médicos. No servirán de base para un autodiagnóstico y tratamiento personal o tratamiento de un tercero sobre la base en la información obtenida a través de la Aplicación Web. Además no constituyen una modalidad de asistencia sanitaria y no sustituyen una consulta médica presencial ni cualquier modalidad de consulta con un médico.</p>
        <p>El Proveedor de Servicios recuerda que la base para el uso de cualquier producto farmacéutico, sólo podrá ser bajo supervisión de  una consulta médica o farmacéutica.</p>
        <p>El Proveedor de Servicios podrá desactivar total o parcialmente las funcionalidades de la Aplicación Web para su reparación o modernización sin previo aviso a los Destinatarios de Servicios. En caso de una desactivación total de las funcionalidades de la Aplicación Web, se publicará un aviso correspondiente en el sitio web del Proveedor de Servicios.</p>
      <p><strong>EL PRESTADOR DE SERVICIOS NO SERÁ RESPONSABLE DE:</strong></p>  
      <ul>
      	<li>las acciones u omisiones de los Destinatarios de Servicios en relación con la información obtenida a través de la Aplicación Web</li>
      	<li>las acciones u omisiones de un tercero para el que el Destinatario de Servicios realizó un Diágnostico Virtual en relación con la información obtenida a través de la Aplicación Web</li>
      	<li>el incumplimiento o el cumplimiento indebido de las obligaciones derivadas del Contrato, resultante de equipos o programas informáticos defectuosos del Destinatario de Servicios</li>
      	<li>la autenticidad, fiabilidad, exactitud e integridad de los datos e información publicados en la Aplicación Web por los Destinatarios de Servicios</li>
      	<li>los daños causados por la acción de terceros, de los que el Proveedor de Servicios no es responsable</li>
      	<li>los daños causados en relación con la venta de productos y la prestación de servicios a los que se refieren los contenidos publicitarios, promocionales e informativos publicados en la Aplicación Web, en particular los productos y servicios ejecutados de forma indebida, contraria a las normas exigidas e infringiendo las disposiciones de la ley o que carezcan de las propiedades ofrecidas</li>
      	<li>las interrupciones en el funcionamiento de la Aplicación Web por motivos ajenos a la responsabilidad del Proveedor de Servicios.</li>
      	<li>cualquier daño causado por el uso del Sitio o la Aplicación por parte de los Destinatarios de Servicios de una manera ilegal o contraria a los Términos y Condiciones</li>
      	<li>los contenidos publicados en los sitios web colocados en otros dominios que no constituyen propiedad del Proveedor de Servicios y a los que se incluyen hipervínculos en el Sitio o la Aplicación. </li>
      	<li>El Proveedor de Servicios no será responsable de los contenidos y textos de los sitios web que no son administrados por el Proveedor de Servicios y a los que se incluyen enlaces en el Sitio o la Aplicación.</li>
      	<li>El Sitio, la Aplicación y la información que los mismos contienen no son y en ningún caso pueden interpretarse como una oferta en el sentido del Código Civil. En caso de publicar cualquier precio, éste se entenderá como una invitación a negociar.</li>
      	<li>El Destinatario de Servicios podrá utilizar los sitios y los servicios de terceros a través del Sitio y la Aplicación utilizando las aplicaciones relacionadas con estos sitios o servicios. El Proveedor de Servicios no será parte de los acuerdos de prestación de servicios por vía electrónica celebrados entre el Destinatario de Servicios y un tercero y no será responsable de estos servicios.</li>
      	<li>La responsabilidad del Proveedor de Servicios por la prestación del Servicio se define en disposiciones legales pertinentes; estos Términos y Condiciones no deberán interpretarse como una base para la concesión de garantías adicionales o ampliación de los derechos del Destinatario de Servicios más allá de los requisitos regulatorios.</li>
      </ul> 
	<p><strong>PROPIEDAD</strong></p><p>Usted no puede declarar propiedad intelectual o exclusiva a ninguno de nuestros productos, modificado o sin modificar. Todos los productos son propiedad &nbsp;de los proveedores del contenido. En caso de que no se especifique lo contrario, nuestros productos se proporcionan&nbsp; sin ningún tipo de garantía, expresa o implícita. En ningún esta compañía será &nbsp;responsables de ningún daño incluyendo, pero no limitado a, daños directos, indirectos, especiales, fortuitos o consecuentes u otras pérdidas resultantes del uso o de la imposibilidad de utilizar nuestros productos.</p>
	<p><strong>POLÍTICA DE REEMBOLSO Y GARANTÍA</strong></p>
	<p>En el caso de productos que sean&nbsp; mercancías irrevocables no-tangibles, no realizamos reembolsos después de que se envíe el producto, usted tiene la responsabilidad de entender antes de comprarlo. &nbsp;Le pedimos que lea cuidadosamente antes de comprarlo. Hacemos solamente excepciones con esta regla cuando la descripción no se ajusta al producto. Hay algunos productos que pudieran tener garantía y posibilidad de reembolso pero este será especificado al comprar el producto. En tales casos la garantía solo cubrirá fallas de fábrica y sólo se hará efectiva cuando el producto se haya usado correctamente. La garantía no cubre averías o daños ocasionados por uso indebido. Los términos de la garantía están asociados a fallas de fabricación y funcionamiento en condiciones normales de los productos y sólo se harán efectivos estos términos si el equipo ha sido usado correctamente. Esto incluye:</p>
	<p>– De acuerdo a las especificaciones técnicas indicadas para cada producto.<br>– En condiciones ambientales acorde con las especificaciones indicadas por el fabricante.<br>– En uso específico para la función con que fue diseñado de fábrica.<br>– En condiciones de operación eléctricas acorde con las especificaciones y tolerancias indicadas.</p>
	<!-- <p><strong>COMPROBACIÓN ANTIFRAUDE</strong></p>
	<p>La compra del cliente puede ser aplazada para la comprobación antifraude. También puede ser suspendida por más tiempo para una investigación más rigurosa, para evitar transacciones fraudulentas.</p> -->
	<p><strong>PRIVACIDAD</strong></p><p>Este https://tumedibot.com garantiza que la <a href="" target="_blank"></a> información personal que usted envía cuenta con la seguridad necesaria. Los datos ingresados por usuario o en el caso de requerir una validación de los pedidos no serán entregados a terceros, salvo que deba ser revelada en cumplimiento a una orden judicial o requerimientos legales.</p>
	<p>La suscripción a boletines de correos electrónicos publicitarios es voluntaria y podría ser seleccionada al momento de crear su cuenta.</p>
	<p>medibot.com reserva los derechos de cambiar o de modificar estos términos sin previo aviso.</p>
	<p>Estas terminos y condiciones se han generado en&nbsp;<a href="http://terminosycondicionesdeusoejemplo.com/" target="_blank">terminosycondicionesdeusoejemplo.com</a>.</p>
	</body>
	</html>
	